#Define UI script for application
shinyUI(fluidPage(
      navbarPage("The Rville Fantasy League",
                  theme = mycss,
                 tabPanel("Home", icon = icon('home'),
                          fluidPage(
                            tags$head(includeScript("www/twittermike.js")),            
                            fluidRow(column(width = 7, img(src = 'crest_final.jpg',
                            width = 200, height = 200, style = "float:left; padding-right:10px"),
                            div(br(), 
                            "Welcome to the RFL web launch and our first inaugeral draft weekend. The RFL is the home of the Richard H. Wharton Memorial Pump Fake Fund. Where one man's crust is another man's dust. It ain't always be what it is, but it do. #TTP", br(),
                            " - Mihir Jr"),
                            br(),br(), br(), br(),
                            includeMarkdown("html/overview.Rmd")
                            ),
                            column(width = 5,
                                   a(class="twitter-timeline", "data-height" = "800",href="https://twitter.com/RFLRumorMill", 
                                     src="//platform.twitter.com/widgets.js"))))),
                 
                 
                 navbarMenu("Analytics", icon = icon('bar-chart'),
                      tabPanel("Rankings", icon = icon('tasks'),
                               fluidPage(fluidRow(column(width= 4,
                                          includeMarkdown("html/rankings.Rmd")),
                                         column(width = 8, 
                                                  DT::dataTableOutput('TeamRankings'))))),

                      
                      tabPanel("Game Logs", icon = icon('google'),
                               fluidPage(fluidRow(column(width = 3,
                                                      selectInput('GM',"Select a Team:",team_list)),
                                                  column(width = 3,
                                                         sliderInput('period',"Choose Time Period:",min = 2011, max = 2016,
                                                                     value = c(2011,2016), sep =""))),
                                         fluidRow(DT::dataTableOutput('gamelogs')))),
                      
                          
                      tabPanel("Playoff Stats", icon = icon('tasks'),
                               DT::dataTableOutput('PlayoffData')),
                      
                      
                      tabPanel("Trend Analysis", icon = icon('line-chart'),
                            fluidPage(fluidRow(column(width = 12,includeMarkdown("html/trend.Rmd"))),
                                      fluidRow(column(width = 3,selectInput('team', "Select a Team:", team_list)),
                                               column(width = 3,sliderInput('year', "Choose Your Timeframe:", min = 2011, max = 2016,value = c(2011,2016), sep =""))),
                                      br(),
                                      fluidRow(column(width = 5,
                                                      DT::dataTableOutput('trend')),
                                              column(width = 6, offset = 1,
                                                      plotlyOutput('barchart')))),
                                      br(), br(), br())),
                 
                 
                  tabPanel("Constitution",
                            tags$iframe(style = "height:1000px; width:100%; scrolling=yes",
                                          src = "constitution.pdf")),
                 
                 
                 tabPanel("Meet the 'Ville",
                          fluidPage(div("Player Profile",
                                      br(), br(), br()),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/fred_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "fred.jpg",width = 300, height = 500))),
                                            br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/rob_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "rob.jpg",width = 300, height = 500))),
                                            br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/chaz_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "chaz.jpg",width = 300, height = 500))),
                                            br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/sean_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "sean.jpg",width = 300, height = 400))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/cory_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "cory.jpg",width = 300, height = 500))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/trev_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "trev.jpg",width = 300, height = 500))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/sammy_desc.Rmd")),
                                               column(width = 4, offset = 1, img(src = "sammy.jpg",width = 300, height = 500))),
                                    br(), br(), br(),
                                     fluidRow(column(width = 7, includeMarkdown("html/bios/bean_desc.Rmd")),
                                               column(width = 4, offset = 1, img(src = "bean.jpg",width = 300, height = 500))),
                                    br(), br(), br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/jay_desc.Rmd")),
                                             column(width = 4, offset = 1, img(src = "jay.jpg",width = 300, height = 500))),
                                    br(),br(),br(),
                                    fluidRow(column(width = 7, includeMarkdown("html/bios/fizz_desc.Rmd")),
                                              column(width = 4, offset = 1, img(src = "fizz.jpg",width = 300, height = 500))),
                                    br(), br(), br(),
                                     fluidRow(column(width = 7, includeMarkdown("html/bios/kev_desc.Rmd")),
                                               column(width = 4, offset = 1, img(src = "kev.jpg",width = 300, height = 500))),
                                     br(), br(), br(),
                                     fluidRow(column(width = 7, includeMarkdown("html/bios/fried_desc.Rmd")),
                                               column(width = 4, offset = 1, img(src = "fried.jpg",width = 300, height = 500))),
                                     br(), br(), br()
                                    )),
                 
                 navbarMenu("Draft Corner", icon = icon('bar-chart'),
                  tabPanel("Historical Results",
                           fluidPage(fluidRow(column(width = 3,
                                                    selectInput('yr',"Select a Year:",c(2016,2015,2014,2013,2012,2011)))),
                                    fluidRow(column(width = 12,
                                                    DT::dataTableOutput('draftgrid'))))),

                  tabPanel("Draft Tendencies",
                          fluidPage(fluidRow(column(width = 12,
                                                    includeMarkdown('html/DraftTrends.Rmd'))),
                                    fluidRow(column(width = 3,selectInput('dtTeam',"Choose General Manager(s):",team_list)),
                                             column(width = 3,selectInput('dtPOS',"Select a Position (Chart Only):",c('QB','WR','RB','TE')))),
                                    br(),br(),
                                    fluidRow(column(width = 5,
                                                    DT::dataTableOutput('Draft')),
                                             column(width = 7,
                                                    plotlyOutput('TrendRound'))),
                                    br())),
                  tabPanel("Player Returns",
                             fluidPage(fluidRow(column(width = 8, includeMarkdown("html/BestDraft.Rmd"))),
                                       fluidRow(column(width = 12, DT::dataTableOutput('TopDraft'))),
                                       fluidRow(column(width = 8,includeMarkdown("html/SeasonReturns.Rmd"))),
                                       fluidRow(column(width = 4,selectInput('SeasonTeam',"Select a General Manager:",team_list)),
                                                column(width = 3,selectInput('SeasonYear',"Select a Season:",c(2016,2015,2014,2013,2012,2011)))),
                                       fluidRow(column(width = 12,DT::dataTableOutput('draftresults'))),
                                       fluidRow(column(width = 8,includeMarkdown('html/RoundReturns.Rmd'))),
                                       fluidRow(column(width = 4,selectInput('RoundTeam',"Select a General Manager:",team_list)),
                                                column(width = 4,sliderInput('RoundYear', "Choose Which Season(s):", min = 2011, max = 2016, value = c(2011,2016), sep =""))),
                                       fluidRow(column(width = 12,DT::dataTableOutput('RdPts'))),
                                       fluidRow(column(width = 8,includeMarkdown('html/PositionReturns.Rmd'))),
                                       fluidRow(column(width = 4, selectInput('PositionTeam',"Select a General Manager:",team_list)),
                                                column(width = 4, sliderInput('PositionYear',"Choose Which Season(s):",min=2011,max=2016,value = c(2011,2016),sep=""))),
                                       fluidRow(column(width = 12, DT::dataTableOutput('PosPts'))),
                                       br(),br()))),
                 tabPanel("Trade Evaulator",
                          includeMarkdown('html/Trades.Rmd'))

)))



