---
title: "bean_desc"
output: html_document
---
### Mike Lorenzo
**Nicknames: "Big Bean", "The Beanstalk", "Stalk"**   
**Years of Service: 6**   
**Championships: 2**    
**Power Rank:**  

The Beanstalk is as big of a perennial douchebag as you can find in the RFL, but unfortunately for the rest of the league, he's just as much of a perennial powerhouse. Although Mike has an astounding 49 wins, that number pales in comparison to the number of piss bottles you could find in his old bedroom. Although he clearly finds everyday value by living in squalor, Mike finds fantasy value plucking crusty running backs up from the waiver wire and winning trades against other marginal players in the league. A member of the mysterious "Council of Elders," Bean has been around since before the live-ball era and is a founder of the league. Currently, Mike has Drake's "Back 2 Back" on repeat as the two-time reigning champion as he looks to map uncharted waters this year by making a bid for the first ever three-peat. 

**Attributes:** Holds onto a few garbage players every year demanding someone trade him for them. Foster & Gordon anyeon? Someone has to need Frank Gore right?   
**Leage Moment:** 2016 - Defeating Robbie by 0.66 points in the Final to complete the first successful Championship Defense in RFL History.**