---
title: "cory_desc"
output: html_document
---
### Cory Mazer
**Nicknames: "Kody", "Seabass", "Bass", "Skinny D"**   
**Years of Service: 6**   
**Championships: 0**    
**Power Rank:**  

Do you pick very boring and cautiously? If so, you might be Cory Mazer. Do you forget to check and set your lineup 5
weeks into the season? If so, you might be Cory Mazer. Is your maximum wager cap $20 or lower? If so, you might be Cory
Mazer. Have you ever missed the playoffs of your main fantasy league 5 straight years, seen a glimmer of hope by finally
finishing the regular season 1st in your 6th year, only to be bounced in the first round? If so, you might be Cory
Mazer. Next time you take a flashlight down into the cellar of your league history, be sure to take a close look,
because you'll more than likely find Cory Mazer.  

**Attributes:** Forgetting to set his lineup one week in the middle of the season and calling it a year from there out.     
**Leage Moment:** 2016 - Cory finally pays attention for a full season, earns the 1st overall seed and bye into Semifinals, ends up losing first playoff game and the 3rd place game earning no monetary prizes for his efforts.