---
title: "fizz_desc"
output: html_document
---
### Brandon Fleming
**Nicknames: "B-Fizz", "Fizz", "CIAB"**   
**Years of Service: 2**   
**Championships: 0**    
**Power Rank:**  

After a degenerate gambling addiction forced the Council of Elders to remove a former league stalwart from the league,
Brandon was given the opportunity to redeem himself for skipping draft day to hit the beach with his mom years back.
After a 4 year exile, Brandon made good on his call to duty by snatching up a playoff birth and profiting nicely off a
9th or better bet from the eventual Mihir Jr. and league imbecile. The Town Center Trench Foot is back this year to show
why he belongs in this league for the longterm, looking to keep his perfect, while small, playoff attendance in tact.
Brandon may be in love with his mom, but even this love is overshadowed by his unwavering dependance on draft magazines.
Earth to Brandon, 2001 called, they want their paperback draft guides back. Will Brandon finally make his first trade
this year? Will he bring leftover CIAB to the draft mansion? Or will he once again be sent back to The Dojo to pick up
the pieces and start all over again? Odds are the Fizz hops off the gain train one stop too early.  

**Attributes:** Not even entertaining the idea of a trade; Purchasing magazines as assistant GMs.   
**Leage Moment:** 2012 - Being exiled from the League for 4 years because he missed the draft from his mom's birthday at the beach.