---
title: "fred_desc"
output: html_document
---

### Fred Ulisse
**Nicknames: "Dump", "Mihir Jr"**   
**Years of Service: 6**   
**Championships: 0**    
**Power Rank:**  

Typically a perennial playoff contender, Fred fell on rough times in 2016 and finished below possibly the worst assembled roster in league history to claim the title of Mihir Jr. He has been an integral member of the RFL since pre-live ball era. Between hosting the early years of The Draft at the Dump, to blacking out before the 5th round of every draft,  where would the league be without it's newest Mihir Club member? As the League's most active trader, many think he agrees to trade for the sole purpose of trading. Regardless, you can count on Mihir Jr. to draft an average team, trade them into a serious contender, and like clockwork, make that one final deal at the deadline that ultimately crushes his Championship hopes. This happens annually.  Will the reigning Mihir regain his form this year? Will the pressure of becoming the League's first back-to-back Mihir become a mental roadblock? Will his feeble attempts at becoming twitter famous with tweets about bobcat vs. human death matches distract him from the prize? Only time will tell.  
  
**Attributes:** Blacking out before Round 5; Trading players just to trade.   
**Leage Moment:** 1A.2016 Singing and recording "One Less Lonely Girl" on Facebook on Valentine's Day for coming in last place.
1B. Getting hit by the backdoor stat correction in the 3rd Place game in 20## to take the L, months after he was paid out, only having to relinquish what he thought were hard earned PowerPoints and cash for nothing. 