---
title: "fried_desc"
output: html_document
---
### Zach Friedman
**Nicknames: "Fried"**   
**Years of Service: 6**   
**Championships: 1**    
**Power Rank:**  

Some reports say Reshard Mendenhall retired early to pursue his passion for writing. Bullshit. Sources close to Reshard
have stated that he indubitably retired because he could not stand being drafted by Zach Friedman for a 5th consecutive
year. Big Fried's drafts are never pretty and usually painfully predictable. All the same, he finds himself in the thick
of things on a consistent basis one way or another. The Friedman phenomenon of 2014 sent shockwaves through the league.
With roughly a 2% chance of making the playoffs in week 13, there was maybe one farfetched scenario for him to advance:
Kevin needed to beat Trevor, Mike needed to lose, and Friedman needed to outscore all of them by 50 points or more.
Somehow ALL of this happened and Friedman dropped 158.32 points, scumming his way into the playoffs with a 6-7 record by
winning the points scored tiebreaker over the other 3. While he may not believe in god, he has no choice but to believe
in miracles. His presence at the draft mansion will be necessary, as many managers may be relying on his physical
therapy skills to revive them back to full health like a pokemon center. Only this time the boys won't be in Saffron
City, they'll be in Ocean City. 

**Attributes:** Scumming out wins with underwhelming rosters.   
**Leage Moment:** 2014 - 'The Friedman Phenomenon'