---
title: "jay_desc"
output: html_document
---
### Jay Rubinstein
**Nicknames: "Mihir I", "The Embellisher"**   
**Years of Service: 6**   
**Championships: 2**    
**Power Rank:**  


Jay is a man who's made his mark by experiencing the highest of highs and the lowest of lows. Jay hit his peak a few years back securing a championship as well as his rightful spot in the council of elders. Shortly after that though, Jays life flipped upside down as he shot to the top of the marriage rankings and the bottom of the fantasy league, nabbing the first ever Mihir G. Patel award. Jay has rebounded since, and the only thing Jay hasn't embellished is his fantasy success. Even though he manages to roster Eddy Lacy and CJ Anderson every year, Jason somehow finds his way into contention and continued success. If a tree falls in the woods and nobody is around to hear it, does it make a noise? If a fantasy mansion party happens, and Jay isn't there to experience the blizzard with his boys, is he even part of the league? Time will tell if Jays belligerent negligence of his friends in favor of his fiance deliver him instant karma in the form of a being Mihir III. 

**Attributes:** Selecting Eddie Lacy every single year.   
**Leage Moment:** 2015 - Completing the first Loser Punishment in RFL history by performing a 5 min stand up comedy act in NYC.