---
title: "kev_desc"
output: html_document
---
### Kevin Burum
**Nicknames: "KB", "The Hiatus", "The Liquor"**   
**Years of Service: 6**   
**Championships: 0**    
**Power Rank:**  

Although Kevin has proclaimed his nickname "The Liquor," his drinking habits are almost as volatile as his general attitude. KB lives his life from hiatus to hiatus, lashing out at anyone who disagrees with his opinions or lifestyle without a second thought. Kevin coined the league sensation known as Trade Tuesdays, but his ability to constantly wheel and deal has only fed into his false proclamation of being the best manager in the league. Sitting at a career 39-39, Kevs record is just like his face back in the days of bell-palsy; equal parts up and down. When he makes the playoffs, he finds himself in the money, but those appearances are few and far between. Another OG on the "Council of Elders," KB is a respected member of the league who has helped shape it into its current and prosperous state. What he lacks in consistent success he makes up for in confidence, so don't be surprised when you find him with more money in side bets than the actual league entry fee.  

**Attributes:** Proposing multiple team trades and having the outcome be way more in his favor than anyone else involved.   
**Leage Moment:** 20## Needing only x points from Vernon Davis, SF Defense, and SF Kicker combined to win the championship and still somehow losing.