---
title: "sammy_desc"
output: html_document
---
### Sammy Sparella
**Nicknames: "Mozz Stick", "Sparelli", "Dusty McCrust"**   
**Years of Service: 6**   
**Championships: 0**    
**Power Rank:**  

Mozzarella Sparella.who's mans is this? When he's not out tricking dusters on tinder, he's offering extremely lopsided trades. Although you can always count on Sammy to remain loyal to the league, his year over year performance and general team makeup is more like his half off apps order from the 'bees; a little bit of everything. In all seriousness though, Sammy's seasons follow a path similar to his day slays, start slow and finish haRd. The mozz-stick king avoids the brunt of the league harassment as he's become very Le'veon Bell-esque in picking his spots to attack other league members. Usually this just means making fun of Chaz. If his players all ran as fast as Sammy talked, he would probably win the league every year. All the same, look for this guy constantly compete for a playoff spot like Jeff Condit constantly competes for Donna's affection at a classic Sparella basement "banger" with the sloppy sophs.  

**Attributes:** Starting off slow, ending the year strong, but rarely making the playoffs; Asking Chaz "How bad is your team?"   
**Leage Moment:** N/A
