---
title: "sean_desc"
output: html_document
---

### Sean Nemazie
**Nicknames: "Treyshauwne"**   
**Years of Service: 6**   
**Championships: 0**    
**Power Rank:**  

The sauciest manager in the league is a member of the original 6 that have seen the league grow from it's infant, immature middle school environment to a possibly more immature adult structure.  Sean has had some rough years battling it out in the basement of the standings, but has found a way to stay out of league infamy by avoiding the dreaded Mihir designation. Sean is also known for his unpredictable and downright contrarian draft strategies, going all in on the entire Patriots team in 2015. It may have worked if he sprinkled a couple of bench players from other teams at the bottom of his roster, but nonetheless Sean will surely have something up his sleeve again this year.  

**Attributes:** Preparing and following through with unnecessarily saucy draft strategies (See Below).  
**Leage Moment:** 2015 - Drafting all New England Patriots for his fantasy team. Started off well, but ended near the bottom of the standings.