---
title: "trev_desc"
output: html_document
---

### Trevor Pittas
**Nicknames: "Unibrow"**   
**Years of Service: 6**   
**Championships: 0**    
**Power Rank:**  

No one knows for sure when, where, or how the Unibrow moniker came to fruition, but like all things, it stays.  An essential asset to the developmental Mihir years of the league, Trev was a force to be reckoned with on the message board and as a team manager. He's been lacking in both of these areas for the past 6 years, making the playoffs only twice, and capturing only 1 third place in that time. Trev has been flying under the radar as one of the worst managers in the league by merit, yet somehow avoids the brunt of ridicule from most of the league. Trevor's free lunch has expired with the League Power Points now transparent for all to see. Will he continue to disappoint or will he rise to the occasion? The 2nd overall pick should help his efforts in 2017. 

**Attributes:** Giving the illusion of always being in contention. Sending NOTDs to reconcile for missing every live draft the league has ever hosted. 
**Leage Moment:** N/A